name: "Assign Reviewers"
on:  
  pull_request:
    types: [ready_for_review]
     
jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team for the review"
      uses: percona-platform/auto-assign-review-teams@v.1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        teams: "pmm-review-exporters"
        skip-with-manual-reviewers: 2
