apiVersion: v1
kind: Pod
metadata:
  name: xbrowsersync
spec:
  containers:
    - name: xbrowsersync
      image: registry.shpaq.org/xbrowsersync:1.1.12
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
