---
apiVersion: v1
kind: Pod
metadata:
  name: xbrowsersync
spec:
  containers:
    - name: xbrowsersync
      image: "registry.shpaq.org/xbrowsersync:v1.1.13"
      imagePullPolicy: Always
      env:
      - name: XBROWSERSYNC_DB_USER
        value: xbrowsersync
      - name: XBROWSERSYNC_DB_PWD
        value: Ef8OnoK3xOIoTAYHo8S9btyllKpdoRYO
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
