FROM python:3.8-slim

RUN apt update && \
    apt upgrade -y
RUN apt install -y apt-utils && \
    apt install -y supervisor python3-dev build-essential python3-pip wget

# Copy project sources
COPY . /src

# Set working directory
WORKDIR /src

RUN pip3 download --dest "/tmp/packages" -r requirements.txt && \
    wget -qO pynacl.tar.gz https://github.com/pyca/pynacl/archive/1.4.0.tar.gz && \
    mkdir pynacl && tar --strip-components=1 -xvf pynacl.tar.gz -C pynacl && rm pynacl.tar.gz
RUN cd pynacl && \
    patch < ../PyNaCl-remove-check.patch && \
    python3 setup.py sdist && \
    cp -f dist/PyNaCl-1.4.0.tar.gz /tmp/packages/

RUN pip3 install --upgrade pip && \
    pip3 install -r requirements.txt && \
    rm -rf /tmp/packages

# Install app dependencies and create supervisord dirs
RUN mkdir -p /etc/supervisor/conf.d /var/log/supervisor /var/run/supervisor

# Copy configuration files
RUN cp /src/deployment/logging.conf /src/logging.conf && \
    cp /src/deployment/gunicorn.conf /src/gunicorn.conf && \
    cp /src/deployment/supervisord.conf /etc/supervisor/supervisord.conf && \
    cp /src/deployment/gunicorn.conf /etc/supervisor/conf.d/gunicorn.conf

# Fix permissions
RUN chgrp -R 0 /src /var/log/supervisor /var/run/supervisor && \
    chmod -R g=u  /src /var/log/supervisor /var/run/supervisor

## Remove repos and unneeded packages
RUN apt -y remove --autoremove build-essential python3-dev && \
    rm -rf /var/lib/apt/lists/*
# Expose service port
EXPOSE 5000

# Start processes
CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
